### ISSUE TITLE
[Feature Request] Locally save installed plugin readme's for offline view!

### ISSUE THREAD

**Issue by Droyk** [TfTHacker/obsidian42-HelpMate#6]
As of now there's seems to be no other community or core plugin that does this important task. there's also a request for it on the [obsidian forums](https://forum.obsidian.md/t/make-installed-community-plugin-information-available-offline/53879/6)

I would be grateful if you could consider this feature request and potentially explore the feasibility of incorporating sub-features within this broader request, like the addition of user notes, as outlined in the obsidian forum discussion. This could potentially enhance the overall user experience when working with plugins offline.

**Comment by TfTHacker** [comment]
This is a very good idea but is beyond the scope of the plugin. Even Obsidian's help is online only 😀.

The problem is you then need some kind of file format that plugins would need to intentionally build for, and this seems like it will be too much to ask for from devs.

I'd suggest submitting a feature request to the Obsidian team for offline help and to include a feature like HelpMate, so all plugin devs can provide local help in a consistent way. Then we can archive Helpmate 😘
